# ---------------------------------------------------------
#  SITEMAP
#  Minimal, explicit configuration.
# ---------------------------------------------------------

changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
