# ---------------------------------------------------------
#  DEVELOPMENT CONFIGURATION
# ---------------------------------------------------------

environment = "development"

# Build drafts during development
buildDrafts = true
buildFuture = true
buildExpired = true

# Faster builds, skip heavy processing
disableFastRender = false

[[module.imports]]
  path = "github.com/matharel/seb-doc/main"

[module]
  replacements = 'github.com/matharel/seb-doc/main -> ../../../themes/seb-doc/clean-js'
