# ---------------------------------------------------------
#  PRODUCTION CONFIGURATION
# ---------------------------------------------------------

environment = "production"

# Ignore drafts
buildDrafts = false
buildFuture = false
buildExpired = false

# Ensure everything is fully rebuilt
disableFastRender = true

# Does not seem very relevant
# cleanDestinationDir = true https://discourse.gohugo.io/t/cleandestinationdir-and-hidden-files/32716

[[module.imports]]
  path = "github.com/matharel/seb-doc/main"

[module]
  replacements = 'github.com/matharel/seb-doc/main -> ../../../themes/seb-doc/main'
